### PR TITLE
README rewrite & project rename

### PR DESCRIPTION
**Pull request by clason**

### CODE REVIEW

**Comment by smolck** [comment]
So I'm gonna generalize this PR to do the full project rename w/user-facing commands and such as well as update the README. Not sure on what we want after `Uivonim` in the header at the top of the README, so for now I've just put nothing. Also, the re-wording for the intro paragraph and the list of "Goals" is still TBD, so if you have any suggestions, just throw them here and we can polish it.

I'm also thinking we may want to move screenshots and such to a different repo, but I'm not sure if that's really necessary; thoughts?

Also, I think we'll just have a single screenshot in the README, and put everything else in the wiki on the new repo once that's up. And same for `docs/`, no need to have a user guide there anymore, we can just put it in the wiki.

**Comment by clason** [comment]
Yeah, looks good! (Although I mentioned electron on purpose to put the toad out in the open :P Avoid "eww, I didn't realize this was *electron*" posts...)

As a goal, I'd maybe also mention exposing the GUI elements via a Lua API for LSP/fuzzy pickers/etc.

Re screenshots: for a plugin, I'd agree, but I don't think it'll make a big difference for a source repo. It also depends on whether you want people to view the README locally, and it's easier to make PRs with screenshots if they're on the same branch or in the same repo. You also want to strike a balance between having enough shiny screenshots on the front page to get people interested and pushing important information down on the page. So I'd start with one or two screenshots showing the main GUI elements, and the rest in a "Gallery" page on the Wiki, as you suggest. (Certainly Nyancat is better moved to Wiki ;))

I see you decided on replacing all(?) veonim occurrences in the code (which is certainly easier to deal with, but check if you missed some, since the case is not consistent). But maybe you'd like to abbreviate some of them (`uvn` or `Uvn` instead of `Uivonim`)?

**Comment by smolck** [comment]
> Yeah, looks good! (Although I mentioned electron on purpose to put the toad out in the open :P Avoid "eww, I didn't realize this was electron" posts...)

Good point, I’ll add the mention of electron back, didn’t realize I’d removed it.

> As a goal, I'd maybe also mention exposing the GUI elements via a Lua API for LSP/fuzzy pickers/etc.
>
> Re screenshots: for a plugin, I'd agree, but I don't think it'll make a big difference for a source repo. It also depends on whether you want people to view the README locally, and it's easier to make PRs with screenshots if they're on the same branch or in the same repo. You also want to strike a balance between having enough shiny screenshots on the front page to get people interested and pushing important information down on the page. So I'd start with one or two screenshots showing the main GUI elements, and the rest in a "Gallery" page on the Wiki, as you suggest. (Certainly Nyancat is better moved to Wiki ;))

:+1:

> I see you decided on replacing all(?) veonim occurrences in the code (which is certainly easier to deal with, but check if you missed some, since the case is not consistent). But maybe you'd like to abbreviate some of them (uvn or Uvn instead of Uivonim)?

So I didn’t actually replace all of them I don’t think, just the ones necessary so that g: variables, commands, and functions (all user-facing) don’t have veonim/vn in them, which required some internal code changing. And good idea on the abbreviation, I just couldn’t think of one in the moment; I may leave it though, considering how those variables aren’t used all that much and it keeps consistency.

**Comment by clason** [comment]
> So I didn’t actually replace all of them I don’t think, just the ones necessary so that g: variables, commands, and functions (all user-facing) don’t have veonim/vn in them, which required some internal code changing.

Ah, that makes sense. I'd still suggest replacing those with `vn` with `uvn` rather than the full name.

**Comment by smolck** [comment]
> Ah, that makes sense. I'd still suggest replacing those with vn with uvn rather than the full name.

Sounds good! Feel free to do that if you want ;)

**Comment by smolck** [comment]
I'm thinking that I'll merge this fairly soon for the code changes, and then we can create another one a bit later for screenshots and more fine-tuning where necessary (after I make the changes you suggested). Reason being, I'd like to add at least the base amount of features for the builtin LSP (signature help, hover, and a few others) so that we can showcase those in the screenshot(s); at the moment using the old ones is kind of deceptive because it won't look the same in the current form, so I think re-taking them would make sense. I don't want to deal with code conflicts when I add those features though, so that's why I want to merge these code changes (maybe should be separate, but not a big deal), and then once those are added, we can add screenshots.

**Comment by clason** [comment]
Yes, that makes sense. Go ahead!

**Pull request merged**
